server.port=9030

# --env rules_api_url= http://host.docker.internal:9004
access-point.rules-api-url=${rules_api_url:http://localhost:9004}

# --env layouts_api_url= http://host.docker.internal:9003
access-point.layouts-api-url=${layouts_api_url:http://localhost:9003}